Downloading (…)ain/hyperparams.yaml:   0%|                                                                         | 0.00/2.04k [00:00<?, ?B/s]Downloading (…)ain/hyperparams.yaml: 100%|█████████████████████████████████████████████████████████████████| 2.04k/2.04k [00:00<00:00, 181kB/s]
'(MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /speechbrain/spkrec-xvect-voxceleb/9d96cafa0ede1a84799b67dc9b5645f31f5b7d094e7e4775e5d5c12547883a93?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27embedding_model.ckpt%3B+filename%3D%22embedding_model.ckpt%22%3B&Expires=1699948032&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTk0ODAzMn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zcGVlY2hicmFpbi9zcGtyZWMteHZlY3Qtdm94Y2VsZWIvOWQ5NmNhZmEwZWRlMWE4NDc5OWI2N2RjOWI1NjQ1ZjMxZjViN2QwOTRlN2U0Nzc1ZTVkNWMxMjU0Nzg4M2E5Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=BP-KKu9HJBZKQLjXn9rCOQ80N5Bq1OqaeYmnBUSTyg-k4mUU0tlEiSdoN8ejYeAH2~0eB7FZWpbEzIOx5TunY87vSqbAoFwimQX4FiJuDznySeklQw4c3pN1aLB5uOnAI3LqjPGyfE-U0BR2vxLcNAHpO1YvlLeaIStz0hFjgO30htFkFzTu0afmTiWSsayTIenQmkYaTj4hw7lxh3GYEZgFLqTrfifxfN9gK~B08Xe9QdGN0KysjVIVYEBH-kVTrAnxIfcse3JrUMnPiBpr7-5fYi~jeTMd1-Kd0m9fdjYj~nqjKqI6Gd16kMJYRMcft557X2zLL6BmTqZZK1OQCQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))"), '(Request ID: dbb42fad-71e5-4705-8f91-601b08b278c6)')' thrown while requesting GET https://cdn-lfs.huggingface.co/speechbrain/spkrec-xvect-voxceleb/9d96cafa0ede1a84799b67dc9b5645f31f5b7d094e7e4775e5d5c12547883a93?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27embedding_model.ckpt%3B+filename%3D%22embedding_model.ckpt%22%3B&Expires=1699948032&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTk0ODAzMn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zcGVlY2hicmFpbi9zcGtyZWMteHZlY3Qtdm94Y2VsZWIvOWQ5NmNhZmEwZWRlMWE4NDc5OWI2N2RjOWI1NjQ1ZjMxZjViN2QwOTRlN2U0Nzc1ZTVkNWMxMjU0Nzg4M2E5Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=BP-KKu9HJBZKQLjXn9rCOQ80N5Bq1OqaeYmnBUSTyg-k4mUU0tlEiSdoN8ejYeAH2%7E0eB7FZWpbEzIOx5TunY87vSqbAoFwimQX4FiJuDznySeklQw4c3pN1aLB5uOnAI3LqjPGyfE-U0BR2vxLcNAHpO1YvlLeaIStz0hFjgO30htFkFzTu0afmTiWSsayTIenQmkYaTj4hw7lxh3GYEZgFLqTrfifxfN9gK%7EB08Xe9QdGN0KysjVIVYEBH-kVTrAnxIfcse3JrUMnPiBpr7-5fYi%7EjeTMd1-Kd0m9fdjYj%7EnqjKqI6Gd16kMJYRMcft557X2zLL6BmTqZZK1OQCQ__&Key-Pair-Id=KVTP0A1DKRTAX
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/py38/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/py38/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/py38/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1114: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /speechbrain/spkrec-xvect-voxceleb/9d96cafa0ede1a84799b67dc9b5645f31f5b7d094e7e4775e5d5c12547883a93?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27embedding_model.ckpt%3B+filename%3D%22embedding_model.ckpt%22%3B&Expires=1699948032&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTk0ODAzMn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zcGVlY2hicmFpbi9zcGtyZWMteHZlY3Qtdm94Y2VsZWIvOWQ5NmNhZmEwZWRlMWE4NDc5OWI2N2RjOWI1NjQ1ZjMxZjViN2QwOTRlN2U0Nzc1ZTVkNWMxMjU0Nzg4M2E5Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=BP-KKu9HJBZKQLjXn9rCOQ80N5Bq1OqaeYmnBUSTyg-k4mUU0tlEiSdoN8ejYeAH2~0eB7FZWpbEzIOx5TunY87vSqbAoFwimQX4FiJuDznySeklQw4c3pN1aLB5uOnAI3LqjPGyfE-U0BR2vxLcNAHpO1YvlLeaIStz0hFjgO30htFkFzTu0afmTiWSsayTIenQmkYaTj4hw7lxh3GYEZgFLqTrfifxfN9gK~B08Xe9QdGN0KysjVIVYEBH-kVTrAnxIfcse3JrUMnPiBpr7-5fYi~jeTMd1-Kd0m9fdjYj~nqjKqI6Gd16kMJYRMcft557X2zLL6BmTqZZK1OQCQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./f00161_classify_speaker.py", line 56, in <module>
    test_classify_speaker()
  File "./f00161_classify_speaker.py", line 32, in test_classify_speaker
    embeddings = classify_speaker('tests/samples/ASR/spk1_snt1.wav')
  File "./f00161_classify_speaker.py", line 22, in classify_speaker
    classifier = EncoderClassifier.from_hparams(source='speechbrain/spkrec-xvect-voxceleb', savedir='pretrained_models/spkrec-xvect-voxceleb')
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py", line 430, in from_hparams
    run_on_main(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1429, in hf_hub_download
    http_get(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 515, in http_get
    r = _request_wrapper(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 452, in _request_wrapper
    return http_backoff(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 274, in http_backoff
    raise err
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /speechbrain/spkrec-xvect-voxceleb/9d96cafa0ede1a84799b67dc9b5645f31f5b7d094e7e4775e5d5c12547883a93?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27embedding_model.ckpt%3B+filename%3D%22embedding_model.ckpt%22%3B&Expires=1699948032&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTk0ODAzMn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zcGVlY2hicmFpbi9zcGtyZWMteHZlY3Qtdm94Y2VsZWIvOWQ5NmNhZmEwZWRlMWE4NDc5OWI2N2RjOWI1NjQ1ZjMxZjViN2QwOTRlN2U0Nzc1ZTVkNWMxMjU0Nzg4M2E5Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=BP-KKu9HJBZKQLjXn9rCOQ80N5Bq1OqaeYmnBUSTyg-k4mUU0tlEiSdoN8ejYeAH2~0eB7FZWpbEzIOx5TunY87vSqbAoFwimQX4FiJuDznySeklQw4c3pN1aLB5uOnAI3LqjPGyfE-U0BR2vxLcNAHpO1YvlLeaIStz0hFjgO30htFkFzTu0afmTiWSsayTIenQmkYaTj4hw7lxh3GYEZgFLqTrfifxfN9gK~B08Xe9QdGN0KysjVIVYEBH-kVTrAnxIfcse3JrUMnPiBpr7-5fYi~jeTMd1-Kd0m9fdjYj~nqjKqI6Gd16kMJYRMcft557X2zLL6BmTqZZK1OQCQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))"), '(Request ID: dbb42fad-71e5-4705-8f91-601b08b278c6)')
